"""initial schema

Revision ID: afe8c4798178
Revises: 
Create Date: 2026-08-28 13:00:14.753544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'afe8c4798178'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('intentions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('desired_outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CLARIFYING', 'PLANNING', 'ACTIVE', 'COMPLETED', 'PAUSED', name='intentionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentions_user_id'), 'intentions', ['user_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('intention_id', app.models.base.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_intention_id'), 'check_ins', ['intention_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('intention_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_intention_id'), 'conversation_messages', ['intention_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('intention_id', app.models.base.GUID(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_intention_id'), 'decisions', ['intention_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('intention_id', app.models.base.GUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_intention_id'), 'expenses', ['intention_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('intention_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='milestonestatus', native_enum=False, length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_intention_id'), 'milestones', ['intention_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('milestone_id', app.models.base.GUID(), nullable=False),
    sa.Column('intention_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='actionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intention_id'], ['intentions.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_intention_id'), 'actions', ['intention_id'], unique=False)
    op.create_index(op.f('ix_actions_milestone_id'), 'actions', ['milestone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_milestone_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_intention_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_milestones_intention_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_expenses_intention_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_decisions_intention_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_conversation_messages_intention_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_check_ins_intention_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_intentions_user_id'), table_name='intentions')
    op.drop_table('intentions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
